
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  post:
      categories: /categories
      archives: /archives
      tags: /tags
  Papers: /paper
  project: /project
  activity: /activity
  search: /search
  # about: http://www.fooying.com
  # rss: /atom.xml

# Miscelaneous
favicon: Logo.png
logo: Logo.png

share:
    show: false
    img:
    img_alt:
    tip_text: test

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# baidu url js push
baidu_url_js_push: true


# comment extend, support gialk, giscus
# giscus https://giscus.app/zh-CN
comment_extend:
    gitalk:
        enable: true
        owner: Github username
        repo: issue repo name
        admin: github username
        clientID: xxx
        clientSecret: xxx
    giscus:
        enable: false
        repo: data-repo
        repoId: data-repo-id
        dataCategoryId: data-category-id 

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true

#footer
index_page: https://github.com/guiyewang
main_site: https://github.com/guiyewang
github: https://github.com/guiyewang
links_url: /links

# 友情链接
links:
  Fooying: https://www.fooying.com

# project
projects:
  博客:
    url: https://guiyewang.github.io/
    descript: 博客

# activitys
activitys:
  腾讯课堂课程《漏洞攻防与企业安全实例讲解》:
    date: 2018-07-10
    url: https://ke.qq.com/course/342390?tuin=49018ed
    type: 课程

# papers
papers:
    原创翻译：给开发者的终极XSS防护备忘录: https://github.com/fooying/Papers/blob/master/给开发者的终极XSS防护备忘录.pdf
